[package]
name = "bevy_mod_raycast"
version = "0.1.1-alpha.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Ray Casting for the Bevy Engine."
repository = "https://github.com/aevyrie/bevy_mod_raycast/"
keywords = ["gamedev", "graphics", "bevy", "3d", "raycast"]
categories = ["game-engines", "rendering"]

[dependencies]
#bevy = { version = "0.4", default-features = false, features = ["render"] }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "master", default-features = false, features = ["render"] }
rayon = "1.5.0"

[features]
ex = [ "bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy/x11" ]

[[example]]
name = "3d_scene"
required-features = [ "ex" ]
